# Triggers a snapshot build on JitPack for the custom domain.
# Already have a webhook setup, but that won't trigger the build
# for the custom domain.

name: jitpack-build

on:
  push:
    branches: [ main ]

jobs:
  jitpack:

    runs-on: ubuntu-latest

    steps:

    - name: Request main-SNAPSHOT from JitPack
      run: |
        # timeout in 30 seconds to avoid waiting for build
        curl -s -m 30 https://jitpack.io/org/cicirello/rho-mu/main-SNAPSHOT/ || true
